databases:
  - name: maishajunctiondb
    plan: free
    databaseName: maishajunction
    user: maishajunction

services:
  - type: web
    plan: free
    name: maishajunction
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn maishajunction.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: maishajunctiondb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
